/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as NewRouteImport } from './routes/new'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ChangesetsIndexRouteImport } from './routes/changesets/index'
import { Route as ChangesetsIdRouteImport } from './routes/changesets/$id'
import { Route as GapsIndexRouteImport } from './routes/gaps/index'
import { Route as GapsIdRouteImport } from './routes/gaps/$id'
import { Route as GapsNewRouteImport } from './routes/gaps/new'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as GoalsIdRouteImport } from './routes/goals/$id'
import { Route as KpisIndexRouteImport } from './routes/kpis/index'
import { Route as KpisIdRouteImport } from './routes/kpis/$id'
import { Route as ManifestsKindRouteImport } from './routes/manifests/$kind'
import { Route as OperationsIndexRouteImport } from './routes/operations/index'
import { Route as OperationsIdRouteImport } from './routes/operations/$id'
import { Route as OperationsNewRouteImport } from './routes/operations/new'
import { Route as PortfoliosIndexRouteImport } from './routes/portfolios/index'
import { Route as PortfoliosIdRouteImport } from './routes/portfolios/$id'
import { Route as PortfoliosNewRouteImport } from './routes/portfolios/new'
import { Route as PortfoliosPrepareRouteImport } from './routes/portfolios/prepare'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesIdRouteImport } from './routes/programmes/$id'
import { Route as ProgrammesNewRouteImport } from './routes/programmes/new'
import { Route as ProgrammesPrepareRouteImport } from './routes/programmes/prepare'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsPrepareRouteImport } from './routes/projects/prepare'
import { Route as ProjectsStartRouteImport } from './routes/projects/start'
import { Route as ProposalsIndexRouteImport } from './routes/proposals/index'
import { Route as ProposalsIdRouteImport } from './routes/proposals/$id'
import { Route as SheetsIndexRouteImport } from './routes/sheets/index'
import { Route as SheetsKindRouteImport } from './routes/sheets/$kind'
import { Route as SnapshotsIndexRouteImport } from './routes/snapshots/index'
import { Route as GapsIdIndexRouteImport } from './routes/gaps/$id/index'
import { Route as GapsIdEvidenceRouteImport } from './routes/gaps/$id/evidence'
import { Route as GapsIdScopeRouteImport } from './routes/gaps/$id/scope'
import { Route as GapsIdShortfallRouteImport } from './routes/gaps/$id/shortfall'
import { Route as KpisIdIndexRouteImport } from './routes/kpis/$id/index'
import { Route as KpisIdDefinitionRouteImport } from './routes/kpis/$id/definition'
import { Route as KpisIdMetricRouteImport } from './routes/kpis/$id/metric'
import { Route as KpisIdReadingsRouteImport } from './routes/kpis/$id/readings'
import { Route as OperationsIdIndexRouteImport } from './routes/operations/$id/index'
import { Route as OperationsIdAlignmentRouteImport } from './routes/operations/$id/alignment'
import { Route as OperationsIdCharterRouteImport } from './routes/operations/$id/charter'
import { Route as OperationsIdMeasuresRouteImport } from './routes/operations/$id/measures'
import { Route as OperationsIdServiceRouteImport } from './routes/operations/$id/service'
import { Route as PortfoliosIdIndexRouteImport } from './routes/portfolios/$id/index'
import { Route as PortfoliosIdAimRouteImport } from './routes/portfolios/$id/aim'
import { Route as PortfoliosIdGovernanceRouteImport } from './routes/portfolios/$id/governance'
import { Route as PortfoliosIdHoldsRouteImport } from './routes/portfolios/$id/holds'
import { Route as PortfoliosIdStrategyRouteImport } from './routes/portfolios/$id/strategy'
import { Route as ProgrammesIdIndexRouteImport } from './routes/programmes/$id/index'
import { Route as ProgrammesIdAimRouteImport } from './routes/programmes/$id/aim'
import { Route as ProgrammesIdAlignmentRouteImport } from './routes/programmes/$id/alignment'
import { Route as ProgrammesIdCharterRouteImport } from './routes/programmes/$id/charter'
import { Route as ProgrammesIdComponentsRouteImport } from './routes/programmes/$id/components'
import { Route as ProgrammesIdFrameworkRouteImport } from './routes/programmes/$id/framework'
import { Route as ProgrammesIdPathwayRouteImport } from './routes/programmes/$id/pathway'
import { Route as ProgrammesIdProblemsRouteImport } from './routes/programmes/$id/problems'
import { Route as ProgrammesIdRisksRouteImport } from './routes/programmes/$id/risks'
import { Route as ProgrammesIdStakeholdersRouteImport } from './routes/programmes/$id/stakeholders'
import { Route as ProgrammesIdTeamsRouteImport } from './routes/programmes/$id/teams'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as ProjectsIdCharterRouteImport } from './routes/projects/$id/charter'
import { Route as ProjectsIdClosingRouteImport } from './routes/projects/$id/closing'
import { Route as ProjectsIdFrameworkRouteImport } from './routes/projects/$id/framework'
import { Route as ProjectsIdHandoffRouteImport } from './routes/projects/$id/handoff'
import { Route as ProjectsIdLandingRouteImport } from './routes/projects/$id/landing'
import { Route as ProjectsIdInitiationAimRouteImport } from './routes/projects/$id/initiation/aim'
import { Route as ProjectsIdInitiationApprovalRouteImport } from './routes/projects/$id/initiation/approval'
import { Route as ProjectsIdInitiationBeneficiariesRouteImport } from './routes/projects/$id/initiation/beneficiaries'
import { Route as ProjectsIdInitiationDataRouteImport } from './routes/projects/$id/initiation/data'
import { Route as ProjectsIdInitiationDeliverablesRouteImport } from './routes/projects/$id/initiation/deliverables'
import { Route as ProjectsIdInitiationGoalsRouteImport } from './routes/projects/$id/initiation/goals'
import { Route as ProjectsIdInitiationLandingRouteImport } from './routes/projects/$id/initiation/landing'
import { Route as ProjectsIdInitiationMeasuresRouteImport } from './routes/projects/$id/initiation/measures'
import { Route as ProjectsIdInitiationResourcesRouteImport } from './routes/projects/$id/initiation/resources'
import { Route as ProjectsIdInitiationRisksRouteImport } from './routes/projects/$id/initiation/risks'
import { Route as ProjectsIdInitiationScopeRouteImport } from './routes/projects/$id/initiation/scope'
import { Route as ProjectsIdInitiationStakeholdersRouteImport } from './routes/projects/$id/initiation/stakeholders'
import { Route as ProjectsIdInitiationSuccessRouteImport } from './routes/projects/$id/initiation/success'
import { Route as ProjectsIdInitiationTimelineRouteImport } from './routes/projects/$id/initiation/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesetsIndexRoute = ChangesetsIndexRouteImport.update({
  id: '/changesets/',
  path: '/changesets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesetsIdRoute = ChangesetsIdRouteImport.update({
  id: '/changesets/$id',
  path: '/changesets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIndexRoute = GapsIndexRouteImport.update({
  id: '/gaps/',
  path: '/gaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIdRoute = GapsIdRouteImport.update({
  id: '/gaps/$id',
  path: '/gaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsNewRoute = GapsNewRouteImport.update({
  id: '/gaps/new',
  path: '/gaps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIdRoute = GoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisIndexRoute = KpisIndexRouteImport.update({
  id: '/kpis/',
  path: '/kpis/',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisIdRoute = KpisIdRouteImport.update({
  id: '/kpis/$id',
  path: '/kpis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestsKindRoute = ManifestsKindRouteImport.update({
  id: '/manifests/$kind',
  path: '/manifests/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIdRoute = OperationsIdRouteImport.update({
  id: '/operations/$id',
  path: '/operations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsNewRoute = OperationsNewRouteImport.update({
  id: '/operations/new',
  path: '/operations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosIndexRoute = PortfoliosIndexRouteImport.update({
  id: '/portfolios/',
  path: '/portfolios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosIdRoute = PortfoliosIdRouteImport.update({
  id: '/portfolios/$id',
  path: '/portfolios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosNewRoute = PortfoliosNewRouteImport.update({
  id: '/portfolios/new',
  path: '/portfolios/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosPrepareRoute = PortfoliosPrepareRouteImport.update({
  id: '/portfolios/prepare',
  path: '/portfolios/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIdRoute = ProgrammesIdRouteImport.update({
  id: '/programmes/$id',
  path: '/programmes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesNewRoute = ProgrammesNewRouteImport.update({
  id: '/programmes/new',
  path: '/programmes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesPrepareRoute = ProgrammesPrepareRouteImport.update({
  id: '/programmes/prepare',
  path: '/programmes/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPrepareRoute = ProjectsPrepareRouteImport.update({
  id: '/projects/prepare',
  path: '/projects/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsStartRoute = ProjectsStartRouteImport.update({
  id: '/projects/start',
  path: '/projects/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsIndexRoute = SheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsKindRoute = SheetsKindRouteImport.update({
  id: '/sheets/$kind',
  path: '/sheets/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsIndexRoute = SnapshotsIndexRouteImport.update({
  id: '/snapshots/',
  path: '/snapshots/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIdIndexRoute = GapsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GapsIdRoute,
} as any)
const GapsIdEvidenceRoute = GapsIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => GapsIdRoute,
} as any)
const GapsIdScopeRoute = GapsIdScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => GapsIdRoute,
} as any)
const GapsIdShortfallRoute = GapsIdShortfallRouteImport.update({
  id: '/shortfall',
  path: '/shortfall',
  getParentRoute: () => GapsIdRoute,
} as any)
const KpisIdIndexRoute = KpisIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KpisIdRoute,
} as any)
const KpisIdDefinitionRoute = KpisIdDefinitionRouteImport.update({
  id: '/definition',
  path: '/definition',
  getParentRoute: () => KpisIdRoute,
} as any)
const KpisIdMetricRoute = KpisIdMetricRouteImport.update({
  id: '/metric',
  path: '/metric',
  getParentRoute: () => KpisIdRoute,
} as any)
const KpisIdReadingsRoute = KpisIdReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => KpisIdRoute,
} as any)
const OperationsIdIndexRoute = OperationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsIdRoute,
} as any)
const OperationsIdAlignmentRoute = OperationsIdAlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => OperationsIdRoute,
} as any)
const OperationsIdCharterRoute = OperationsIdCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => OperationsIdRoute,
} as any)
const OperationsIdMeasuresRoute = OperationsIdMeasuresRouteImport.update({
  id: '/measures',
  path: '/measures',
  getParentRoute: () => OperationsIdRoute,
} as any)
const OperationsIdServiceRoute = OperationsIdServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => OperationsIdRoute,
} as any)
const PortfoliosIdIndexRoute = PortfoliosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfoliosIdRoute,
} as any)
const PortfoliosIdAimRoute = PortfoliosIdAimRouteImport.update({
  id: '/aim',
  path: '/aim',
  getParentRoute: () => PortfoliosIdRoute,
} as any)
const PortfoliosIdGovernanceRoute = PortfoliosIdGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => PortfoliosIdRoute,
} as any)
const PortfoliosIdHoldsRoute = PortfoliosIdHoldsRouteImport.update({
  id: '/holds',
  path: '/holds',
  getParentRoute: () => PortfoliosIdRoute,
} as any)
const PortfoliosIdStrategyRoute = PortfoliosIdStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => PortfoliosIdRoute,
} as any)
const ProgrammesIdIndexRoute = ProgrammesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdAimRoute = ProgrammesIdAimRouteImport.update({
  id: '/aim',
  path: '/aim',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdAlignmentRoute = ProgrammesIdAlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdCharterRoute = ProgrammesIdCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdComponentsRoute = ProgrammesIdComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdFrameworkRoute = ProgrammesIdFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdPathwayRoute = ProgrammesIdPathwayRouteImport.update({
  id: '/pathway',
  path: '/pathway',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdProblemsRoute = ProgrammesIdProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdRisksRoute = ProgrammesIdRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProgrammesIdStakeholdersRoute =
  ProgrammesIdStakeholdersRouteImport.update({
    id: '/stakeholders',
    path: '/stakeholders',
    getParentRoute: () => ProgrammesIdRoute,
  } as any)
const ProgrammesIdTeamsRoute = ProgrammesIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ProgrammesIdRoute,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdCharterRoute = ProjectsIdCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdClosingRoute = ProjectsIdClosingRouteImport.update({
  id: '/closing',
  path: '/closing',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdFrameworkRoute = ProjectsIdFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdHandoffRoute = ProjectsIdHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdLandingRoute = ProjectsIdLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdInitiationAimRoute = ProjectsIdInitiationAimRouteImport.update({
  id: '/initiation/aim',
  path: '/initiation/aim',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdInitiationApprovalRoute =
  ProjectsIdInitiationApprovalRouteImport.update({
    id: '/initiation/approval',
    path: '/initiation/approval',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationBeneficiariesRoute =
  ProjectsIdInitiationBeneficiariesRouteImport.update({
    id: '/initiation/beneficiaries',
    path: '/initiation/beneficiaries',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationDataRoute =
  ProjectsIdInitiationDataRouteImport.update({
    id: '/initiation/data',
    path: '/initiation/data',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationDeliverablesRoute =
  ProjectsIdInitiationDeliverablesRouteImport.update({
    id: '/initiation/deliverables',
    path: '/initiation/deliverables',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationGoalsRoute =
  ProjectsIdInitiationGoalsRouteImport.update({
    id: '/initiation/goals',
    path: '/initiation/goals',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationLandingRoute =
  ProjectsIdInitiationLandingRouteImport.update({
    id: '/initiation/landing',
    path: '/initiation/landing',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationMeasuresRoute =
  ProjectsIdInitiationMeasuresRouteImport.update({
    id: '/initiation/measures',
    path: '/initiation/measures',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationResourcesRoute =
  ProjectsIdInitiationResourcesRouteImport.update({
    id: '/initiation/resources',
    path: '/initiation/resources',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationRisksRoute =
  ProjectsIdInitiationRisksRouteImport.update({
    id: '/initiation/risks',
    path: '/initiation/risks',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationScopeRoute =
  ProjectsIdInitiationScopeRouteImport.update({
    id: '/initiation/scope',
    path: '/initiation/scope',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationStakeholdersRoute =
  ProjectsIdInitiationStakeholdersRouteImport.update({
    id: '/initiation/stakeholders',
    path: '/initiation/stakeholders',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationSuccessRoute =
  ProjectsIdInitiationSuccessRouteImport.update({
    id: '/initiation/success',
    path: '/initiation/success',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdInitiationTimelineRoute =
  ProjectsIdInitiationTimelineRouteImport.update({
    id: '/initiation/timeline',
    path: '/initiation/timeline',
    getParentRoute: () => ProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/glossary': typeof GlossaryRoute
  '/graph': typeof GraphRoute
  '/indicators': typeof IndicatorsRoute
  '/new': typeof NewRoute
  '/strategy': typeof StrategyRoute
  '/welcome': typeof WelcomeRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/gaps/$id': typeof GapsIdRouteWithChildren
  '/gaps/new': typeof GapsNewRoute
  '/goals/$id': typeof GoalsIdRoute
  '/kpis/$id': typeof KpisIdRouteWithChildren
  '/manifests/$kind': typeof ManifestsKindRoute
  '/operations/$id': typeof OperationsIdRouteWithChildren
  '/operations/new': typeof OperationsNewRoute
  '/portfolios/$id': typeof PortfoliosIdRouteWithChildren
  '/portfolios/new': typeof PortfoliosNewRoute
  '/portfolios/prepare': typeof PortfoliosPrepareRoute
  '/programmes/$id': typeof ProgrammesIdRouteWithChildren
  '/programmes/new': typeof ProgrammesNewRoute
  '/programmes/prepare': typeof ProgrammesPrepareRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/prepare': typeof ProjectsPrepareRoute
  '/projects/start': typeof ProjectsStartRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sheets/$kind': typeof SheetsKindRoute
  '/changesets/': typeof ChangesetsIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/kpis/': typeof KpisIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/portfolios/': typeof PortfoliosIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/sheets/': typeof SheetsIndexRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/gaps/$id/evidence': typeof GapsIdEvidenceRoute
  '/gaps/$id/scope': typeof GapsIdScopeRoute
  '/gaps/$id/shortfall': typeof GapsIdShortfallRoute
  '/kpis/$id/definition': typeof KpisIdDefinitionRoute
  '/kpis/$id/metric': typeof KpisIdMetricRoute
  '/kpis/$id/readings': typeof KpisIdReadingsRoute
  '/operations/$id/alignment': typeof OperationsIdAlignmentRoute
  '/operations/$id/charter': typeof OperationsIdCharterRoute
  '/operations/$id/measures': typeof OperationsIdMeasuresRoute
  '/operations/$id/service': typeof OperationsIdServiceRoute
  '/portfolios/$id/aim': typeof PortfoliosIdAimRoute
  '/portfolios/$id/governance': typeof PortfoliosIdGovernanceRoute
  '/portfolios/$id/holds': typeof PortfoliosIdHoldsRoute
  '/portfolios/$id/strategy': typeof PortfoliosIdStrategyRoute
  '/programmes/$id/aim': typeof ProgrammesIdAimRoute
  '/programmes/$id/alignment': typeof ProgrammesIdAlignmentRoute
  '/programmes/$id/charter': typeof ProgrammesIdCharterRoute
  '/programmes/$id/components': typeof ProgrammesIdComponentsRoute
  '/programmes/$id/framework': typeof ProgrammesIdFrameworkRoute
  '/programmes/$id/pathway': typeof ProgrammesIdPathwayRoute
  '/programmes/$id/problems': typeof ProgrammesIdProblemsRoute
  '/programmes/$id/risks': typeof ProgrammesIdRisksRoute
  '/programmes/$id/stakeholders': typeof ProgrammesIdStakeholdersRoute
  '/programmes/$id/teams': typeof ProgrammesIdTeamsRoute
  '/projects/$id/charter': typeof ProjectsIdCharterRoute
  '/projects/$id/closing': typeof ProjectsIdClosingRoute
  '/projects/$id/framework': typeof ProjectsIdFrameworkRoute
  '/projects/$id/handoff': typeof ProjectsIdHandoffRoute
  '/projects/$id/landing': typeof ProjectsIdLandingRoute
  '/gaps/$id/': typeof GapsIdIndexRoute
  '/kpis/$id/': typeof KpisIdIndexRoute
  '/operations/$id/': typeof OperationsIdIndexRoute
  '/portfolios/$id/': typeof PortfoliosIdIndexRoute
  '/programmes/$id/': typeof ProgrammesIdIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/initiation/aim': typeof ProjectsIdInitiationAimRoute
  '/projects/$id/initiation/approval': typeof ProjectsIdInitiationApprovalRoute
  '/projects/$id/initiation/beneficiaries': typeof ProjectsIdInitiationBeneficiariesRoute
  '/projects/$id/initiation/data': typeof ProjectsIdInitiationDataRoute
  '/projects/$id/initiation/deliverables': typeof ProjectsIdInitiationDeliverablesRoute
  '/projects/$id/initiation/goals': typeof ProjectsIdInitiationGoalsRoute
  '/projects/$id/initiation/landing': typeof ProjectsIdInitiationLandingRoute
  '/projects/$id/initiation/measures': typeof ProjectsIdInitiationMeasuresRoute
  '/projects/$id/initiation/resources': typeof ProjectsIdInitiationResourcesRoute
  '/projects/$id/initiation/risks': typeof ProjectsIdInitiationRisksRoute
  '/projects/$id/initiation/scope': typeof ProjectsIdInitiationScopeRoute
  '/projects/$id/initiation/stakeholders': typeof ProjectsIdInitiationStakeholdersRoute
  '/projects/$id/initiation/success': typeof ProjectsIdInitiationSuccessRoute
  '/projects/$id/initiation/timeline': typeof ProjectsIdInitiationTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/glossary': typeof GlossaryRoute
  '/graph': typeof GraphRoute
  '/indicators': typeof IndicatorsRoute
  '/new': typeof NewRoute
  '/strategy': typeof StrategyRoute
  '/welcome': typeof WelcomeRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/gaps/new': typeof GapsNewRoute
  '/goals/$id': typeof GoalsIdRoute
  '/manifests/$kind': typeof ManifestsKindRoute
  '/operations/new': typeof OperationsNewRoute
  '/portfolios/new': typeof PortfoliosNewRoute
  '/portfolios/prepare': typeof PortfoliosPrepareRoute
  '/programmes/new': typeof ProgrammesNewRoute
  '/programmes/prepare': typeof ProgrammesPrepareRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/prepare': typeof ProjectsPrepareRoute
  '/projects/start': typeof ProjectsStartRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sheets/$kind': typeof SheetsKindRoute
  '/changesets': typeof ChangesetsIndexRoute
  '/gaps': typeof GapsIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/kpis': typeof KpisIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/portfolios': typeof PortfoliosIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/proposals': typeof ProposalsIndexRoute
  '/sheets': typeof SheetsIndexRoute
  '/snapshots': typeof SnapshotsIndexRoute
  '/gaps/$id/evidence': typeof GapsIdEvidenceRoute
  '/gaps/$id/scope': typeof GapsIdScopeRoute
  '/gaps/$id/shortfall': typeof GapsIdShortfallRoute
  '/kpis/$id/definition': typeof KpisIdDefinitionRoute
  '/kpis/$id/metric': typeof KpisIdMetricRoute
  '/kpis/$id/readings': typeof KpisIdReadingsRoute
  '/operations/$id/alignment': typeof OperationsIdAlignmentRoute
  '/operations/$id/charter': typeof OperationsIdCharterRoute
  '/operations/$id/measures': typeof OperationsIdMeasuresRoute
  '/operations/$id/service': typeof OperationsIdServiceRoute
  '/portfolios/$id/aim': typeof PortfoliosIdAimRoute
  '/portfolios/$id/governance': typeof PortfoliosIdGovernanceRoute
  '/portfolios/$id/holds': typeof PortfoliosIdHoldsRoute
  '/portfolios/$id/strategy': typeof PortfoliosIdStrategyRoute
  '/programmes/$id/aim': typeof ProgrammesIdAimRoute
  '/programmes/$id/alignment': typeof ProgrammesIdAlignmentRoute
  '/programmes/$id/charter': typeof ProgrammesIdCharterRoute
  '/programmes/$id/components': typeof ProgrammesIdComponentsRoute
  '/programmes/$id/framework': typeof ProgrammesIdFrameworkRoute
  '/programmes/$id/pathway': typeof ProgrammesIdPathwayRoute
  '/programmes/$id/problems': typeof ProgrammesIdProblemsRoute
  '/programmes/$id/risks': typeof ProgrammesIdRisksRoute
  '/programmes/$id/stakeholders': typeof ProgrammesIdStakeholdersRoute
  '/programmes/$id/teams': typeof ProgrammesIdTeamsRoute
  '/projects/$id/charter': typeof ProjectsIdCharterRoute
  '/projects/$id/closing': typeof ProjectsIdClosingRoute
  '/projects/$id/framework': typeof ProjectsIdFrameworkRoute
  '/projects/$id/handoff': typeof ProjectsIdHandoffRoute
  '/projects/$id/landing': typeof ProjectsIdLandingRoute
  '/gaps/$id': typeof GapsIdIndexRoute
  '/kpis/$id': typeof KpisIdIndexRoute
  '/operations/$id': typeof OperationsIdIndexRoute
  '/portfolios/$id': typeof PortfoliosIdIndexRoute
  '/programmes/$id': typeof ProgrammesIdIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/initiation/aim': typeof ProjectsIdInitiationAimRoute
  '/projects/$id/initiation/approval': typeof ProjectsIdInitiationApprovalRoute
  '/projects/$id/initiation/beneficiaries': typeof ProjectsIdInitiationBeneficiariesRoute
  '/projects/$id/initiation/data': typeof ProjectsIdInitiationDataRoute
  '/projects/$id/initiation/deliverables': typeof ProjectsIdInitiationDeliverablesRoute
  '/projects/$id/initiation/goals': typeof ProjectsIdInitiationGoalsRoute
  '/projects/$id/initiation/landing': typeof ProjectsIdInitiationLandingRoute
  '/projects/$id/initiation/measures': typeof ProjectsIdInitiationMeasuresRoute
  '/projects/$id/initiation/resources': typeof ProjectsIdInitiationResourcesRoute
  '/projects/$id/initiation/risks': typeof ProjectsIdInitiationRisksRoute
  '/projects/$id/initiation/scope': typeof ProjectsIdInitiationScopeRoute
  '/projects/$id/initiation/stakeholders': typeof ProjectsIdInitiationStakeholdersRoute
  '/projects/$id/initiation/success': typeof ProjectsIdInitiationSuccessRoute
  '/projects/$id/initiation/timeline': typeof ProjectsIdInitiationTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/glossary': typeof GlossaryRoute
  '/graph': typeof GraphRoute
  '/indicators': typeof IndicatorsRoute
  '/new': typeof NewRoute
  '/strategy': typeof StrategyRoute
  '/welcome': typeof WelcomeRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/gaps/$id': typeof GapsIdRouteWithChildren
  '/gaps/new': typeof GapsNewRoute
  '/goals/$id': typeof GoalsIdRoute
  '/kpis/$id': typeof KpisIdRouteWithChildren
  '/manifests/$kind': typeof ManifestsKindRoute
  '/operations/$id': typeof OperationsIdRouteWithChildren
  '/operations/new': typeof OperationsNewRoute
  '/portfolios/$id': typeof PortfoliosIdRouteWithChildren
  '/portfolios/new': typeof PortfoliosNewRoute
  '/portfolios/prepare': typeof PortfoliosPrepareRoute
  '/programmes/$id': typeof ProgrammesIdRouteWithChildren
  '/programmes/new': typeof ProgrammesNewRoute
  '/programmes/prepare': typeof ProgrammesPrepareRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/prepare': typeof ProjectsPrepareRoute
  '/projects/start': typeof ProjectsStartRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sheets/$kind': typeof SheetsKindRoute
  '/changesets/': typeof ChangesetsIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/kpis/': typeof KpisIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/portfolios/': typeof PortfoliosIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/sheets/': typeof SheetsIndexRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/gaps/$id/evidence': typeof GapsIdEvidenceRoute
  '/gaps/$id/scope': typeof GapsIdScopeRoute
  '/gaps/$id/shortfall': typeof GapsIdShortfallRoute
  '/kpis/$id/definition': typeof KpisIdDefinitionRoute
  '/kpis/$id/metric': typeof KpisIdMetricRoute
  '/kpis/$id/readings': typeof KpisIdReadingsRoute
  '/operations/$id/alignment': typeof OperationsIdAlignmentRoute
  '/operations/$id/charter': typeof OperationsIdCharterRoute
  '/operations/$id/measures': typeof OperationsIdMeasuresRoute
  '/operations/$id/service': typeof OperationsIdServiceRoute
  '/portfolios/$id/aim': typeof PortfoliosIdAimRoute
  '/portfolios/$id/governance': typeof PortfoliosIdGovernanceRoute
  '/portfolios/$id/holds': typeof PortfoliosIdHoldsRoute
  '/portfolios/$id/strategy': typeof PortfoliosIdStrategyRoute
  '/programmes/$id/aim': typeof ProgrammesIdAimRoute
  '/programmes/$id/alignment': typeof ProgrammesIdAlignmentRoute
  '/programmes/$id/charter': typeof ProgrammesIdCharterRoute
  '/programmes/$id/components': typeof ProgrammesIdComponentsRoute
  '/programmes/$id/framework': typeof ProgrammesIdFrameworkRoute
  '/programmes/$id/pathway': typeof ProgrammesIdPathwayRoute
  '/programmes/$id/problems': typeof ProgrammesIdProblemsRoute
  '/programmes/$id/risks': typeof ProgrammesIdRisksRoute
  '/programmes/$id/stakeholders': typeof ProgrammesIdStakeholdersRoute
  '/programmes/$id/teams': typeof ProgrammesIdTeamsRoute
  '/projects/$id/charter': typeof ProjectsIdCharterRoute
  '/projects/$id/closing': typeof ProjectsIdClosingRoute
  '/projects/$id/framework': typeof ProjectsIdFrameworkRoute
  '/projects/$id/handoff': typeof ProjectsIdHandoffRoute
  '/projects/$id/landing': typeof ProjectsIdLandingRoute
  '/gaps/$id/': typeof GapsIdIndexRoute
  '/kpis/$id/': typeof KpisIdIndexRoute
  '/operations/$id/': typeof OperationsIdIndexRoute
  '/portfolios/$id/': typeof PortfoliosIdIndexRoute
  '/programmes/$id/': typeof ProgrammesIdIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/initiation/aim': typeof ProjectsIdInitiationAimRoute
  '/projects/$id/initiation/approval': typeof ProjectsIdInitiationApprovalRoute
  '/projects/$id/initiation/beneficiaries': typeof ProjectsIdInitiationBeneficiariesRoute
  '/projects/$id/initiation/data': typeof ProjectsIdInitiationDataRoute
  '/projects/$id/initiation/deliverables': typeof ProjectsIdInitiationDeliverablesRoute
  '/projects/$id/initiation/goals': typeof ProjectsIdInitiationGoalsRoute
  '/projects/$id/initiation/landing': typeof ProjectsIdInitiationLandingRoute
  '/projects/$id/initiation/measures': typeof ProjectsIdInitiationMeasuresRoute
  '/projects/$id/initiation/resources': typeof ProjectsIdInitiationResourcesRoute
  '/projects/$id/initiation/risks': typeof ProjectsIdInitiationRisksRoute
  '/projects/$id/initiation/scope': typeof ProjectsIdInitiationScopeRoute
  '/projects/$id/initiation/stakeholders': typeof ProjectsIdInitiationStakeholdersRoute
  '/projects/$id/initiation/success': typeof ProjectsIdInitiationSuccessRoute
  '/projects/$id/initiation/timeline': typeof ProjectsIdInitiationTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/agents'
    | '/glossary'
    | '/graph'
    | '/indicators'
    | '/new'
    | '/strategy'
    | '/welcome'
    | '/changesets/$id'
    | '/gaps/$id'
    | '/gaps/new'
    | '/goals/$id'
    | '/kpis/$id'
    | '/manifests/$kind'
    | '/operations/$id'
    | '/operations/new'
    | '/portfolios/$id'
    | '/portfolios/new'
    | '/portfolios/prepare'
    | '/programmes/$id'
    | '/programmes/new'
    | '/programmes/prepare'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/prepare'
    | '/projects/start'
    | '/proposals/$id'
    | '/sheets/$kind'
    | '/changesets/'
    | '/gaps/'
    | '/goals/'
    | '/kpis/'
    | '/operations/'
    | '/portfolios/'
    | '/programmes/'
    | '/projects/'
    | '/proposals/'
    | '/sheets/'
    | '/snapshots/'
    | '/gaps/$id/evidence'
    | '/gaps/$id/scope'
    | '/gaps/$id/shortfall'
    | '/kpis/$id/definition'
    | '/kpis/$id/metric'
    | '/kpis/$id/readings'
    | '/operations/$id/alignment'
    | '/operations/$id/charter'
    | '/operations/$id/measures'
    | '/operations/$id/service'
    | '/portfolios/$id/aim'
    | '/portfolios/$id/governance'
    | '/portfolios/$id/holds'
    | '/portfolios/$id/strategy'
    | '/programmes/$id/aim'
    | '/programmes/$id/alignment'
    | '/programmes/$id/charter'
    | '/programmes/$id/components'
    | '/programmes/$id/framework'
    | '/programmes/$id/pathway'
    | '/programmes/$id/problems'
    | '/programmes/$id/risks'
    | '/programmes/$id/stakeholders'
    | '/programmes/$id/teams'
    | '/projects/$id/charter'
    | '/projects/$id/closing'
    | '/projects/$id/framework'
    | '/projects/$id/handoff'
    | '/projects/$id/landing'
    | '/gaps/$id/'
    | '/kpis/$id/'
    | '/operations/$id/'
    | '/portfolios/$id/'
    | '/programmes/$id/'
    | '/projects/$id/'
    | '/projects/$id/initiation/aim'
    | '/projects/$id/initiation/approval'
    | '/projects/$id/initiation/beneficiaries'
    | '/projects/$id/initiation/data'
    | '/projects/$id/initiation/deliverables'
    | '/projects/$id/initiation/goals'
    | '/projects/$id/initiation/landing'
    | '/projects/$id/initiation/measures'
    | '/projects/$id/initiation/resources'
    | '/projects/$id/initiation/risks'
    | '/projects/$id/initiation/scope'
    | '/projects/$id/initiation/stakeholders'
    | '/projects/$id/initiation/success'
    | '/projects/$id/initiation/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/agents'
    | '/glossary'
    | '/graph'
    | '/indicators'
    | '/new'
    | '/strategy'
    | '/welcome'
    | '/changesets/$id'
    | '/gaps/new'
    | '/goals/$id'
    | '/manifests/$kind'
    | '/operations/new'
    | '/portfolios/new'
    | '/portfolios/prepare'
    | '/programmes/new'
    | '/programmes/prepare'
    | '/projects/new'
    | '/projects/prepare'
    | '/projects/start'
    | '/proposals/$id'
    | '/sheets/$kind'
    | '/changesets'
    | '/gaps'
    | '/goals'
    | '/kpis'
    | '/operations'
    | '/portfolios'
    | '/programmes'
    | '/projects'
    | '/proposals'
    | '/sheets'
    | '/snapshots'
    | '/gaps/$id/evidence'
    | '/gaps/$id/scope'
    | '/gaps/$id/shortfall'
    | '/kpis/$id/definition'
    | '/kpis/$id/metric'
    | '/kpis/$id/readings'
    | '/operations/$id/alignment'
    | '/operations/$id/charter'
    | '/operations/$id/measures'
    | '/operations/$id/service'
    | '/portfolios/$id/aim'
    | '/portfolios/$id/governance'
    | '/portfolios/$id/holds'
    | '/portfolios/$id/strategy'
    | '/programmes/$id/aim'
    | '/programmes/$id/alignment'
    | '/programmes/$id/charter'
    | '/programmes/$id/components'
    | '/programmes/$id/framework'
    | '/programmes/$id/pathway'
    | '/programmes/$id/problems'
    | '/programmes/$id/risks'
    | '/programmes/$id/stakeholders'
    | '/programmes/$id/teams'
    | '/projects/$id/charter'
    | '/projects/$id/closing'
    | '/projects/$id/framework'
    | '/projects/$id/handoff'
    | '/projects/$id/landing'
    | '/gaps/$id'
    | '/kpis/$id'
    | '/operations/$id'
    | '/portfolios/$id'
    | '/programmes/$id'
    | '/projects/$id'
    | '/projects/$id/initiation/aim'
    | '/projects/$id/initiation/approval'
    | '/projects/$id/initiation/beneficiaries'
    | '/projects/$id/initiation/data'
    | '/projects/$id/initiation/deliverables'
    | '/projects/$id/initiation/goals'
    | '/projects/$id/initiation/landing'
    | '/projects/$id/initiation/measures'
    | '/projects/$id/initiation/resources'
    | '/projects/$id/initiation/risks'
    | '/projects/$id/initiation/scope'
    | '/projects/$id/initiation/stakeholders'
    | '/projects/$id/initiation/success'
    | '/projects/$id/initiation/timeline'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/agents'
    | '/glossary'
    | '/graph'
    | '/indicators'
    | '/new'
    | '/strategy'
    | '/welcome'
    | '/changesets/$id'
    | '/gaps/$id'
    | '/gaps/new'
    | '/goals/$id'
    | '/kpis/$id'
    | '/manifests/$kind'
    | '/operations/$id'
    | '/operations/new'
    | '/portfolios/$id'
    | '/portfolios/new'
    | '/portfolios/prepare'
    | '/programmes/$id'
    | '/programmes/new'
    | '/programmes/prepare'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/prepare'
    | '/projects/start'
    | '/proposals/$id'
    | '/sheets/$kind'
    | '/changesets/'
    | '/gaps/'
    | '/goals/'
    | '/kpis/'
    | '/operations/'
    | '/portfolios/'
    | '/programmes/'
    | '/projects/'
    | '/proposals/'
    | '/sheets/'
    | '/snapshots/'
    | '/gaps/$id/evidence'
    | '/gaps/$id/scope'
    | '/gaps/$id/shortfall'
    | '/kpis/$id/definition'
    | '/kpis/$id/metric'
    | '/kpis/$id/readings'
    | '/operations/$id/alignment'
    | '/operations/$id/charter'
    | '/operations/$id/measures'
    | '/operations/$id/service'
    | '/portfolios/$id/aim'
    | '/portfolios/$id/governance'
    | '/portfolios/$id/holds'
    | '/portfolios/$id/strategy'
    | '/programmes/$id/aim'
    | '/programmes/$id/alignment'
    | '/programmes/$id/charter'
    | '/programmes/$id/components'
    | '/programmes/$id/framework'
    | '/programmes/$id/pathway'
    | '/programmes/$id/problems'
    | '/programmes/$id/risks'
    | '/programmes/$id/stakeholders'
    | '/programmes/$id/teams'
    | '/projects/$id/charter'
    | '/projects/$id/closing'
    | '/projects/$id/framework'
    | '/projects/$id/handoff'
    | '/projects/$id/landing'
    | '/gaps/$id/'
    | '/kpis/$id/'
    | '/operations/$id/'
    | '/portfolios/$id/'
    | '/programmes/$id/'
    | '/projects/$id/'
    | '/projects/$id/initiation/aim'
    | '/projects/$id/initiation/approval'
    | '/projects/$id/initiation/beneficiaries'
    | '/projects/$id/initiation/data'
    | '/projects/$id/initiation/deliverables'
    | '/projects/$id/initiation/goals'
    | '/projects/$id/initiation/landing'
    | '/projects/$id/initiation/measures'
    | '/projects/$id/initiation/resources'
    | '/projects/$id/initiation/risks'
    | '/projects/$id/initiation/scope'
    | '/projects/$id/initiation/stakeholders'
    | '/projects/$id/initiation/success'
    | '/projects/$id/initiation/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AgentsRoute: typeof AgentsRoute
  GlossaryRoute: typeof GlossaryRoute
  GraphRoute: typeof GraphRoute
  IndicatorsRoute: typeof IndicatorsRoute
  NewRoute: typeof NewRoute
  StrategyRoute: typeof StrategyRoute
  WelcomeRoute: typeof WelcomeRoute
  ChangesetsIdRoute: typeof ChangesetsIdRoute
  GapsIdRoute: typeof GapsIdRouteWithChildren
  GapsNewRoute: typeof GapsNewRoute
  GoalsIdRoute: typeof GoalsIdRoute
  KpisIdRoute: typeof KpisIdRouteWithChildren
  ManifestsKindRoute: typeof ManifestsKindRoute
  OperationsIdRoute: typeof OperationsIdRouteWithChildren
  OperationsNewRoute: typeof OperationsNewRoute
  PortfoliosIdRoute: typeof PortfoliosIdRouteWithChildren
  PortfoliosNewRoute: typeof PortfoliosNewRoute
  PortfoliosPrepareRoute: typeof PortfoliosPrepareRoute
  ProgrammesIdRoute: typeof ProgrammesIdRouteWithChildren
  ProgrammesNewRoute: typeof ProgrammesNewRoute
  ProgrammesPrepareRoute: typeof ProgrammesPrepareRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsPrepareRoute: typeof ProjectsPrepareRoute
  ProjectsStartRoute: typeof ProjectsStartRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
  SheetsKindRoute: typeof SheetsKindRoute
  ChangesetsIndexRoute: typeof ChangesetsIndexRoute
  GapsIndexRoute: typeof GapsIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  KpisIndexRoute: typeof KpisIndexRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  PortfoliosIndexRoute: typeof PortfoliosIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
  SheetsIndexRoute: typeof SheetsIndexRoute
  SnapshotsIndexRoute: typeof SnapshotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changesets/': {
      id: '/changesets/'
      path: '/changesets'
      fullPath: '/changesets/'
      preLoaderRoute: typeof ChangesetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changesets/$id': {
      id: '/changesets/$id'
      path: '/changesets/$id'
      fullPath: '/changesets/$id'
      preLoaderRoute: typeof ChangesetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/': {
      id: '/gaps/'
      path: '/gaps'
      fullPath: '/gaps/'
      preLoaderRoute: typeof GapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/$id': {
      id: '/gaps/$id'
      path: '/gaps/$id'
      fullPath: '/gaps/$id'
      preLoaderRoute: typeof GapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/new': {
      id: '/gaps/new'
      path: '/gaps/new'
      fullPath: '/gaps/new'
      preLoaderRoute: typeof GapsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$id': {
      id: '/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof GoalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis/': {
      id: '/kpis/'
      path: '/kpis'
      fullPath: '/kpis/'
      preLoaderRoute: typeof KpisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis/$id': {
      id: '/kpis/$id'
      path: '/kpis/$id'
      fullPath: '/kpis/$id'
      preLoaderRoute: typeof KpisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifests/$kind': {
      id: '/manifests/$kind'
      path: '/manifests/$kind'
      fullPath: '/manifests/$kind'
      preLoaderRoute: typeof ManifestsKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/$id': {
      id: '/operations/$id'
      path: '/operations/$id'
      fullPath: '/operations/$id'
      preLoaderRoute: typeof OperationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/new': {
      id: '/operations/new'
      path: '/operations/new'
      fullPath: '/operations/new'
      preLoaderRoute: typeof OperationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/': {
      id: '/portfolios/'
      path: '/portfolios'
      fullPath: '/portfolios/'
      preLoaderRoute: typeof PortfoliosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/$id': {
      id: '/portfolios/$id'
      path: '/portfolios/$id'
      fullPath: '/portfolios/$id'
      preLoaderRoute: typeof PortfoliosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/new': {
      id: '/portfolios/new'
      path: '/portfolios/new'
      fullPath: '/portfolios/new'
      preLoaderRoute: typeof PortfoliosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/prepare': {
      id: '/portfolios/prepare'
      path: '/portfolios/prepare'
      fullPath: '/portfolios/prepare'
      preLoaderRoute: typeof PortfoliosPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$id': {
      id: '/programmes/$id'
      path: '/programmes/$id'
      fullPath: '/programmes/$id'
      preLoaderRoute: typeof ProgrammesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/new': {
      id: '/programmes/new'
      path: '/programmes/new'
      fullPath: '/programmes/new'
      preLoaderRoute: typeof ProgrammesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/prepare': {
      id: '/programmes/prepare'
      path: '/programmes/prepare'
      fullPath: '/programmes/prepare'
      preLoaderRoute: typeof ProgrammesPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/prepare': {
      id: '/projects/prepare'
      path: '/projects/prepare'
      fullPath: '/projects/prepare'
      preLoaderRoute: typeof ProjectsPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/start': {
      id: '/projects/start'
      path: '/projects/start'
      fullPath: '/projects/start'
      preLoaderRoute: typeof ProjectsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets/': {
      id: '/sheets/'
      path: '/sheets'
      fullPath: '/sheets/'
      preLoaderRoute: typeof SheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets/$kind': {
      id: '/sheets/$kind'
      path: '/sheets/$kind'
      fullPath: '/sheets/$kind'
      preLoaderRoute: typeof SheetsKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/': {
      id: '/snapshots/'
      path: '/snapshots'
      fullPath: '/snapshots/'
      preLoaderRoute: typeof SnapshotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/$id/': {
      id: '/gaps/$id/'
      path: '/'
      fullPath: '/gaps/$id/'
      preLoaderRoute: typeof GapsIdIndexRouteImport
      parentRoute: typeof GapsIdRoute
    }
    '/gaps/$id/evidence': {
      id: '/gaps/$id/evidence'
      path: '/evidence'
      fullPath: '/gaps/$id/evidence'
      preLoaderRoute: typeof GapsIdEvidenceRouteImport
      parentRoute: typeof GapsIdRoute
    }
    '/gaps/$id/scope': {
      id: '/gaps/$id/scope'
      path: '/scope'
      fullPath: '/gaps/$id/scope'
      preLoaderRoute: typeof GapsIdScopeRouteImport
      parentRoute: typeof GapsIdRoute
    }
    '/gaps/$id/shortfall': {
      id: '/gaps/$id/shortfall'
      path: '/shortfall'
      fullPath: '/gaps/$id/shortfall'
      preLoaderRoute: typeof GapsIdShortfallRouteImport
      parentRoute: typeof GapsIdRoute
    }
    '/kpis/$id/': {
      id: '/kpis/$id/'
      path: '/'
      fullPath: '/kpis/$id/'
      preLoaderRoute: typeof KpisIdIndexRouteImport
      parentRoute: typeof KpisIdRoute
    }
    '/kpis/$id/definition': {
      id: '/kpis/$id/definition'
      path: '/definition'
      fullPath: '/kpis/$id/definition'
      preLoaderRoute: typeof KpisIdDefinitionRouteImport
      parentRoute: typeof KpisIdRoute
    }
    '/kpis/$id/metric': {
      id: '/kpis/$id/metric'
      path: '/metric'
      fullPath: '/kpis/$id/metric'
      preLoaderRoute: typeof KpisIdMetricRouteImport
      parentRoute: typeof KpisIdRoute
    }
    '/kpis/$id/readings': {
      id: '/kpis/$id/readings'
      path: '/readings'
      fullPath: '/kpis/$id/readings'
      preLoaderRoute: typeof KpisIdReadingsRouteImport
      parentRoute: typeof KpisIdRoute
    }
    '/operations/$id/': {
      id: '/operations/$id/'
      path: '/'
      fullPath: '/operations/$id/'
      preLoaderRoute: typeof OperationsIdIndexRouteImport
      parentRoute: typeof OperationsIdRoute
    }
    '/operations/$id/alignment': {
      id: '/operations/$id/alignment'
      path: '/alignment'
      fullPath: '/operations/$id/alignment'
      preLoaderRoute: typeof OperationsIdAlignmentRouteImport
      parentRoute: typeof OperationsIdRoute
    }
    '/operations/$id/charter': {
      id: '/operations/$id/charter'
      path: '/charter'
      fullPath: '/operations/$id/charter'
      preLoaderRoute: typeof OperationsIdCharterRouteImport
      parentRoute: typeof OperationsIdRoute
    }
    '/operations/$id/measures': {
      id: '/operations/$id/measures'
      path: '/measures'
      fullPath: '/operations/$id/measures'
      preLoaderRoute: typeof OperationsIdMeasuresRouteImport
      parentRoute: typeof OperationsIdRoute
    }
    '/operations/$id/service': {
      id: '/operations/$id/service'
      path: '/service'
      fullPath: '/operations/$id/service'
      preLoaderRoute: typeof OperationsIdServiceRouteImport
      parentRoute: typeof OperationsIdRoute
    }
    '/portfolios/$id/': {
      id: '/portfolios/$id/'
      path: '/'
      fullPath: '/portfolios/$id/'
      preLoaderRoute: typeof PortfoliosIdIndexRouteImport
      parentRoute: typeof PortfoliosIdRoute
    }
    '/portfolios/$id/aim': {
      id: '/portfolios/$id/aim'
      path: '/aim'
      fullPath: '/portfolios/$id/aim'
      preLoaderRoute: typeof PortfoliosIdAimRouteImport
      parentRoute: typeof PortfoliosIdRoute
    }
    '/portfolios/$id/governance': {
      id: '/portfolios/$id/governance'
      path: '/governance'
      fullPath: '/portfolios/$id/governance'
      preLoaderRoute: typeof PortfoliosIdGovernanceRouteImport
      parentRoute: typeof PortfoliosIdRoute
    }
    '/portfolios/$id/holds': {
      id: '/portfolios/$id/holds'
      path: '/holds'
      fullPath: '/portfolios/$id/holds'
      preLoaderRoute: typeof PortfoliosIdHoldsRouteImport
      parentRoute: typeof PortfoliosIdRoute
    }
    '/portfolios/$id/strategy': {
      id: '/portfolios/$id/strategy'
      path: '/strategy'
      fullPath: '/portfolios/$id/strategy'
      preLoaderRoute: typeof PortfoliosIdStrategyRouteImport
      parentRoute: typeof PortfoliosIdRoute
    }
    '/programmes/$id/': {
      id: '/programmes/$id/'
      path: '/'
      fullPath: '/programmes/$id/'
      preLoaderRoute: typeof ProgrammesIdIndexRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/aim': {
      id: '/programmes/$id/aim'
      path: '/aim'
      fullPath: '/programmes/$id/aim'
      preLoaderRoute: typeof ProgrammesIdAimRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/alignment': {
      id: '/programmes/$id/alignment'
      path: '/alignment'
      fullPath: '/programmes/$id/alignment'
      preLoaderRoute: typeof ProgrammesIdAlignmentRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/charter': {
      id: '/programmes/$id/charter'
      path: '/charter'
      fullPath: '/programmes/$id/charter'
      preLoaderRoute: typeof ProgrammesIdCharterRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/components': {
      id: '/programmes/$id/components'
      path: '/components'
      fullPath: '/programmes/$id/components'
      preLoaderRoute: typeof ProgrammesIdComponentsRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/framework': {
      id: '/programmes/$id/framework'
      path: '/framework'
      fullPath: '/programmes/$id/framework'
      preLoaderRoute: typeof ProgrammesIdFrameworkRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/pathway': {
      id: '/programmes/$id/pathway'
      path: '/pathway'
      fullPath: '/programmes/$id/pathway'
      preLoaderRoute: typeof ProgrammesIdPathwayRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/problems': {
      id: '/programmes/$id/problems'
      path: '/problems'
      fullPath: '/programmes/$id/problems'
      preLoaderRoute: typeof ProgrammesIdProblemsRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/risks': {
      id: '/programmes/$id/risks'
      path: '/risks'
      fullPath: '/programmes/$id/risks'
      preLoaderRoute: typeof ProgrammesIdRisksRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/stakeholders': {
      id: '/programmes/$id/stakeholders'
      path: '/stakeholders'
      fullPath: '/programmes/$id/stakeholders'
      preLoaderRoute: typeof ProgrammesIdStakeholdersRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/programmes/$id/teams': {
      id: '/programmes/$id/teams'
      path: '/teams'
      fullPath: '/programmes/$id/teams'
      preLoaderRoute: typeof ProgrammesIdTeamsRouteImport
      parentRoute: typeof ProgrammesIdRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/charter': {
      id: '/projects/$id/charter'
      path: '/charter'
      fullPath: '/projects/$id/charter'
      preLoaderRoute: typeof ProjectsIdCharterRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/closing': {
      id: '/projects/$id/closing'
      path: '/closing'
      fullPath: '/projects/$id/closing'
      preLoaderRoute: typeof ProjectsIdClosingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/framework': {
      id: '/projects/$id/framework'
      path: '/framework'
      fullPath: '/projects/$id/framework'
      preLoaderRoute: typeof ProjectsIdFrameworkRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/handoff': {
      id: '/projects/$id/handoff'
      path: '/handoff'
      fullPath: '/projects/$id/handoff'
      preLoaderRoute: typeof ProjectsIdHandoffRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/landing': {
      id: '/projects/$id/landing'
      path: '/landing'
      fullPath: '/projects/$id/landing'
      preLoaderRoute: typeof ProjectsIdLandingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/aim': {
      id: '/projects/$id/initiation/aim'
      path: '/initiation/aim'
      fullPath: '/projects/$id/initiation/aim'
      preLoaderRoute: typeof ProjectsIdInitiationAimRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/approval': {
      id: '/projects/$id/initiation/approval'
      path: '/initiation/approval'
      fullPath: '/projects/$id/initiation/approval'
      preLoaderRoute: typeof ProjectsIdInitiationApprovalRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/beneficiaries': {
      id: '/projects/$id/initiation/beneficiaries'
      path: '/initiation/beneficiaries'
      fullPath: '/projects/$id/initiation/beneficiaries'
      preLoaderRoute: typeof ProjectsIdInitiationBeneficiariesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/data': {
      id: '/projects/$id/initiation/data'
      path: '/initiation/data'
      fullPath: '/projects/$id/initiation/data'
      preLoaderRoute: typeof ProjectsIdInitiationDataRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/deliverables': {
      id: '/projects/$id/initiation/deliverables'
      path: '/initiation/deliverables'
      fullPath: '/projects/$id/initiation/deliverables'
      preLoaderRoute: typeof ProjectsIdInitiationDeliverablesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/goals': {
      id: '/projects/$id/initiation/goals'
      path: '/initiation/goals'
      fullPath: '/projects/$id/initiation/goals'
      preLoaderRoute: typeof ProjectsIdInitiationGoalsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/landing': {
      id: '/projects/$id/initiation/landing'
      path: '/initiation/landing'
      fullPath: '/projects/$id/initiation/landing'
      preLoaderRoute: typeof ProjectsIdInitiationLandingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/measures': {
      id: '/projects/$id/initiation/measures'
      path: '/initiation/measures'
      fullPath: '/projects/$id/initiation/measures'
      preLoaderRoute: typeof ProjectsIdInitiationMeasuresRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/resources': {
      id: '/projects/$id/initiation/resources'
      path: '/initiation/resources'
      fullPath: '/projects/$id/initiation/resources'
      preLoaderRoute: typeof ProjectsIdInitiationResourcesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/risks': {
      id: '/projects/$id/initiation/risks'
      path: '/initiation/risks'
      fullPath: '/projects/$id/initiation/risks'
      preLoaderRoute: typeof ProjectsIdInitiationRisksRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/scope': {
      id: '/projects/$id/initiation/scope'
      path: '/initiation/scope'
      fullPath: '/projects/$id/initiation/scope'
      preLoaderRoute: typeof ProjectsIdInitiationScopeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/stakeholders': {
      id: '/projects/$id/initiation/stakeholders'
      path: '/initiation/stakeholders'
      fullPath: '/projects/$id/initiation/stakeholders'
      preLoaderRoute: typeof ProjectsIdInitiationStakeholdersRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/success': {
      id: '/projects/$id/initiation/success'
      path: '/initiation/success'
      fullPath: '/projects/$id/initiation/success'
      preLoaderRoute: typeof ProjectsIdInitiationSuccessRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/initiation/timeline': {
      id: '/projects/$id/initiation/timeline'
      path: '/initiation/timeline'
      fullPath: '/projects/$id/initiation/timeline'
      preLoaderRoute: typeof ProjectsIdInitiationTimelineRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface GapsIdRouteChildren {
  GapsIdEvidenceRoute: typeof GapsIdEvidenceRoute
  GapsIdScopeRoute: typeof GapsIdScopeRoute
  GapsIdShortfallRoute: typeof GapsIdShortfallRoute
  GapsIdIndexRoute: typeof GapsIdIndexRoute
}

const GapsIdRouteChildren: GapsIdRouteChildren = {
  GapsIdEvidenceRoute: GapsIdEvidenceRoute,
  GapsIdScopeRoute: GapsIdScopeRoute,
  GapsIdShortfallRoute: GapsIdShortfallRoute,
  GapsIdIndexRoute: GapsIdIndexRoute,
}

const GapsIdRouteWithChildren =
  GapsIdRoute._addFileChildren(GapsIdRouteChildren)

interface KpisIdRouteChildren {
  KpisIdDefinitionRoute: typeof KpisIdDefinitionRoute
  KpisIdMetricRoute: typeof KpisIdMetricRoute
  KpisIdReadingsRoute: typeof KpisIdReadingsRoute
  KpisIdIndexRoute: typeof KpisIdIndexRoute
}

const KpisIdRouteChildren: KpisIdRouteChildren = {
  KpisIdDefinitionRoute: KpisIdDefinitionRoute,
  KpisIdMetricRoute: KpisIdMetricRoute,
  KpisIdReadingsRoute: KpisIdReadingsRoute,
  KpisIdIndexRoute: KpisIdIndexRoute,
}

const KpisIdRouteWithChildren =
  KpisIdRoute._addFileChildren(KpisIdRouteChildren)

interface OperationsIdRouteChildren {
  OperationsIdAlignmentRoute: typeof OperationsIdAlignmentRoute
  OperationsIdCharterRoute: typeof OperationsIdCharterRoute
  OperationsIdMeasuresRoute: typeof OperationsIdMeasuresRoute
  OperationsIdServiceRoute: typeof OperationsIdServiceRoute
  OperationsIdIndexRoute: typeof OperationsIdIndexRoute
}

const OperationsIdRouteChildren: OperationsIdRouteChildren = {
  OperationsIdAlignmentRoute: OperationsIdAlignmentRoute,
  OperationsIdCharterRoute: OperationsIdCharterRoute,
  OperationsIdMeasuresRoute: OperationsIdMeasuresRoute,
  OperationsIdServiceRoute: OperationsIdServiceRoute,
  OperationsIdIndexRoute: OperationsIdIndexRoute,
}

const OperationsIdRouteWithChildren = OperationsIdRoute._addFileChildren(
  OperationsIdRouteChildren,
)

interface PortfoliosIdRouteChildren {
  PortfoliosIdAimRoute: typeof PortfoliosIdAimRoute
  PortfoliosIdGovernanceRoute: typeof PortfoliosIdGovernanceRoute
  PortfoliosIdHoldsRoute: typeof PortfoliosIdHoldsRoute
  PortfoliosIdStrategyRoute: typeof PortfoliosIdStrategyRoute
  PortfoliosIdIndexRoute: typeof PortfoliosIdIndexRoute
}

const PortfoliosIdRouteChildren: PortfoliosIdRouteChildren = {
  PortfoliosIdAimRoute: PortfoliosIdAimRoute,
  PortfoliosIdGovernanceRoute: PortfoliosIdGovernanceRoute,
  PortfoliosIdHoldsRoute: PortfoliosIdHoldsRoute,
  PortfoliosIdStrategyRoute: PortfoliosIdStrategyRoute,
  PortfoliosIdIndexRoute: PortfoliosIdIndexRoute,
}

const PortfoliosIdRouteWithChildren = PortfoliosIdRoute._addFileChildren(
  PortfoliosIdRouteChildren,
)

interface ProgrammesIdRouteChildren {
  ProgrammesIdAimRoute: typeof ProgrammesIdAimRoute
  ProgrammesIdAlignmentRoute: typeof ProgrammesIdAlignmentRoute
  ProgrammesIdCharterRoute: typeof ProgrammesIdCharterRoute
  ProgrammesIdComponentsRoute: typeof ProgrammesIdComponentsRoute
  ProgrammesIdFrameworkRoute: typeof ProgrammesIdFrameworkRoute
  ProgrammesIdPathwayRoute: typeof ProgrammesIdPathwayRoute
  ProgrammesIdProblemsRoute: typeof ProgrammesIdProblemsRoute
  ProgrammesIdRisksRoute: typeof ProgrammesIdRisksRoute
  ProgrammesIdStakeholdersRoute: typeof ProgrammesIdStakeholdersRoute
  ProgrammesIdTeamsRoute: typeof ProgrammesIdTeamsRoute
  ProgrammesIdIndexRoute: typeof ProgrammesIdIndexRoute
}

const ProgrammesIdRouteChildren: ProgrammesIdRouteChildren = {
  ProgrammesIdAimRoute: ProgrammesIdAimRoute,
  ProgrammesIdAlignmentRoute: ProgrammesIdAlignmentRoute,
  ProgrammesIdCharterRoute: ProgrammesIdCharterRoute,
  ProgrammesIdComponentsRoute: ProgrammesIdComponentsRoute,
  ProgrammesIdFrameworkRoute: ProgrammesIdFrameworkRoute,
  ProgrammesIdPathwayRoute: ProgrammesIdPathwayRoute,
  ProgrammesIdProblemsRoute: ProgrammesIdProblemsRoute,
  ProgrammesIdRisksRoute: ProgrammesIdRisksRoute,
  ProgrammesIdStakeholdersRoute: ProgrammesIdStakeholdersRoute,
  ProgrammesIdTeamsRoute: ProgrammesIdTeamsRoute,
  ProgrammesIdIndexRoute: ProgrammesIdIndexRoute,
}

const ProgrammesIdRouteWithChildren = ProgrammesIdRoute._addFileChildren(
  ProgrammesIdRouteChildren,
)

interface ProjectsIdRouteChildren {
  ProjectsIdCharterRoute: typeof ProjectsIdCharterRoute
  ProjectsIdClosingRoute: typeof ProjectsIdClosingRoute
  ProjectsIdFrameworkRoute: typeof ProjectsIdFrameworkRoute
  ProjectsIdHandoffRoute: typeof ProjectsIdHandoffRoute
  ProjectsIdLandingRoute: typeof ProjectsIdLandingRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdInitiationAimRoute: typeof ProjectsIdInitiationAimRoute
  ProjectsIdInitiationApprovalRoute: typeof ProjectsIdInitiationApprovalRoute
  ProjectsIdInitiationBeneficiariesRoute: typeof ProjectsIdInitiationBeneficiariesRoute
  ProjectsIdInitiationDataRoute: typeof ProjectsIdInitiationDataRoute
  ProjectsIdInitiationDeliverablesRoute: typeof ProjectsIdInitiationDeliverablesRoute
  ProjectsIdInitiationGoalsRoute: typeof ProjectsIdInitiationGoalsRoute
  ProjectsIdInitiationLandingRoute: typeof ProjectsIdInitiationLandingRoute
  ProjectsIdInitiationMeasuresRoute: typeof ProjectsIdInitiationMeasuresRoute
  ProjectsIdInitiationResourcesRoute: typeof ProjectsIdInitiationResourcesRoute
  ProjectsIdInitiationRisksRoute: typeof ProjectsIdInitiationRisksRoute
  ProjectsIdInitiationScopeRoute: typeof ProjectsIdInitiationScopeRoute
  ProjectsIdInitiationStakeholdersRoute: typeof ProjectsIdInitiationStakeholdersRoute
  ProjectsIdInitiationSuccessRoute: typeof ProjectsIdInitiationSuccessRoute
  ProjectsIdInitiationTimelineRoute: typeof ProjectsIdInitiationTimelineRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdCharterRoute: ProjectsIdCharterRoute,
  ProjectsIdClosingRoute: ProjectsIdClosingRoute,
  ProjectsIdFrameworkRoute: ProjectsIdFrameworkRoute,
  ProjectsIdHandoffRoute: ProjectsIdHandoffRoute,
  ProjectsIdLandingRoute: ProjectsIdLandingRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdInitiationAimRoute: ProjectsIdInitiationAimRoute,
  ProjectsIdInitiationApprovalRoute: ProjectsIdInitiationApprovalRoute,
  ProjectsIdInitiationBeneficiariesRoute:
    ProjectsIdInitiationBeneficiariesRoute,
  ProjectsIdInitiationDataRoute: ProjectsIdInitiationDataRoute,
  ProjectsIdInitiationDeliverablesRoute: ProjectsIdInitiationDeliverablesRoute,
  ProjectsIdInitiationGoalsRoute: ProjectsIdInitiationGoalsRoute,
  ProjectsIdInitiationLandingRoute: ProjectsIdInitiationLandingRoute,
  ProjectsIdInitiationMeasuresRoute: ProjectsIdInitiationMeasuresRoute,
  ProjectsIdInitiationResourcesRoute: ProjectsIdInitiationResourcesRoute,
  ProjectsIdInitiationRisksRoute: ProjectsIdInitiationRisksRoute,
  ProjectsIdInitiationScopeRoute: ProjectsIdInitiationScopeRoute,
  ProjectsIdInitiationStakeholdersRoute: ProjectsIdInitiationStakeholdersRoute,
  ProjectsIdInitiationSuccessRoute: ProjectsIdInitiationSuccessRoute,
  ProjectsIdInitiationTimelineRoute: ProjectsIdInitiationTimelineRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AgentsRoute: AgentsRoute,
  GlossaryRoute: GlossaryRoute,
  GraphRoute: GraphRoute,
  IndicatorsRoute: IndicatorsRoute,
  NewRoute: NewRoute,
  StrategyRoute: StrategyRoute,
  WelcomeRoute: WelcomeRoute,
  ChangesetsIdRoute: ChangesetsIdRoute,
  GapsIdRoute: GapsIdRouteWithChildren,
  GapsNewRoute: GapsNewRoute,
  GoalsIdRoute: GoalsIdRoute,
  KpisIdRoute: KpisIdRouteWithChildren,
  ManifestsKindRoute: ManifestsKindRoute,
  OperationsIdRoute: OperationsIdRouteWithChildren,
  OperationsNewRoute: OperationsNewRoute,
  PortfoliosIdRoute: PortfoliosIdRouteWithChildren,
  PortfoliosNewRoute: PortfoliosNewRoute,
  PortfoliosPrepareRoute: PortfoliosPrepareRoute,
  ProgrammesIdRoute: ProgrammesIdRouteWithChildren,
  ProgrammesNewRoute: ProgrammesNewRoute,
  ProgrammesPrepareRoute: ProgrammesPrepareRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsPrepareRoute: ProjectsPrepareRoute,
  ProjectsStartRoute: ProjectsStartRoute,
  ProposalsIdRoute: ProposalsIdRoute,
  SheetsKindRoute: SheetsKindRoute,
  ChangesetsIndexRoute: ChangesetsIndexRoute,
  GapsIndexRoute: GapsIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  KpisIndexRoute: KpisIndexRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  PortfoliosIndexRoute: PortfoliosIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
  SheetsIndexRoute: SheetsIndexRoute,
  SnapshotsIndexRoute: SnapshotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
